### ISSUE TITLE
None of the flags in the docs actually exist?

### ISSUE THREAD

**Issue by oskapt** [kvaps/kubectl-build#1]
HI - I wanted to cover this on Coffee and Cloud Native today, because I had Kaniko on the show last week. I ran through it last night, and it seems that none of the samples in your README actually work. I looked in the script, and the flags aren't even there. Is there some prerequisite that's missing from the installation guide, or was the README made from a different branch/version?

```
root@training-a:/var/tmp/build# kubectl build --context . --no-push
/usr/local/bin/kubectl-build: 72: /usr/local/bin/kubectl-build: args+="--no-push", : not found

root@training-a:/var/tmp/build# kubectl build --help
/usr/local/bin/kubectl-build: 72: /usr/local/bin/kubectl-build: args+="--help", : not found

root@training-a:/var/tmp/build# kubectl build -c . -d docker.io/monachus/build-test:latest
/usr/local/bin/kubectl-build: 72: /usr/local/bin/kubectl-build: args+="-d", : not found
```

**Comment by kvaps** [comment]
Hi, thanks for the report!
Could you please specify your OS, and
```
/bin/sh --version
```

**Comment by kvaps** [comment]
I gues you were using dash on ubuntu or debian, compatibility should be fixed in https://github.com/kvaps/kubectl-build/commit/c12b568fd326298156b9d1648bca22bb5b1387fb
