### ISSUE TITLE
Feat: Add option to specify Dockerfile

### ISSUE THREAD

**Issue by jpambrun** [kvaps/kubectl-build#7]
Add a `--dockerfile=Dockerfile` flag to maps kaniko's `--dockerfile` argument.

Sorry of the numerous issues. I hope to use this and to be able to recommend it to my coworkers. I just want to document the missing bits.

**Comment by kvaps** [comment]
I'm sure that any kaniko flag should be forwarded, just try specifying `--dockerfile=Dockerfile`:
```
kubectl build -c . --no-push --dockerfile=Dockerfile
```

> Sorry of the numerous issues. I hope to use this and to be able to recommend it to my coworkers. I just want to document the missing bits.

Please don't stop 😀

**Comment by jpambrun** [comment]
Yep. That works. Thanks. It wasn't obvious from parsing to shell script or reading the doc.
